### ISSUE TITLE
Typo "BradcastStyle"?

### ISSUE THREAD

**Issue by dronir** [haberdashPI/MetaArrays.jl#1]
I was just reading through the code because I was interested to see how the broadcasting is implemented, and noticed what I assume is a typo.

https://github.com/haberdashPI/MetaArrays.jl/blob/bd312ec6983b5d80e8e18ced65ad20ce4cccac98/src/MetaArrays.jl#L190

**Comment by haberdashPI** [comment]
So it is. Thank you for catching it! I have been meaning to improve code coverage, and clearly I haven't tested that line yet. I should be able to get to this within the next few days, but can't fix it at the moment.

**Comment by haberdashPI** [comment]
Commit 9140cea630f2fe702cb3519e9b0ea1edc08d937 implements the intended functionality. The failure to properly implement/test this method caused a bug when broadcasting a MetaArray of an array that implemented custom broadcast machinery (e.g. [StaticArrays](https://github.com/JuliaArrays/StaticArrays.jl)).
