### ISSUE TITLE
Deprecate getcontents in favor of parent? 

### ISSUE THREAD

**Issue by jishnub** [haberdashPI/MetaArrays.jl#6]
It's conventional to use `parent` in Array wrappers to extract the underlying array, eg. in `OffsetArray` or `AxisArray`. In this case the same function appears to be carried out by `getcontents`. Would it be possible to shift to `parent` to conform with other packages?

Since it is exported, this may only be changed in the next minor release with a deprecation meanwhile.

**Comment by haberdashPI** [comment]
Good idea! I'm on board with that change.
